apiVersion: v1
kind: Pod
metadata:
  name: posts
spec:
  containers:
    - name: posts
      # image: sha256:e4725edcc9262a14bebd1a0b88600c20830cdf3
      image: docker.io/231615/posts
      imagePullPolicy: Never
